name: sunny_services_example
publish_to: none

environment: 
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  dio: ^4.0.3
  flutter:
    sdk: flutter
  sunny_services:
    path: ../
  buffer: ^1.1.1
  dartxx: ^0.5.4
  flutter_contact: ^0.9.1+8
  floor: ^1.2.0
  http: ^0.13.4
  stream_transform: ^2.0.0
  pfile_picker: ^3.1.4+2
  firebase: ^9.0.2
  firebase_storage: ^10.1.0
  #build_web_compilers: ^3.2.0
dependency_overrides:
  provider: ^6.0.1

