name: file_upload_service
version: 1.5.1
description: File uploading
repository: https://github.com/ericmartineau/file_upload_service.git
environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies:
  buffer: ^1.1.1
  dartx: ^1.1.0
  dio: ^4.0.6
  http: ^0.13.5
  logging: ^1.1.1
  permission_handler: ^10.2.0
  semaphore: ^0.2.1
  stream_transform: ^2.1.0
  graphql: ^5.1.3
  gql_http_link: ^0.4.2
  grunt_web_worker_gen:
    path: /Users/ericm/reliveit/checkout/ericmartineau/grunt_web_worker_gen
  collection_diff:
    path: /Users/ericm/reliveit/checkout/SunnyApp/collection_diff
  observable_collections:
    path: /Users/ericm/reliveit/checkout/SunnyApp/observable_collections
  logging_config:
    path: /Users/ericm/reliveit/checkout/SunnyApp/logging_config
  pfile:
    path: /Users/ericm/reliveit/checkout/SunnyApp/pfile
  sunny_service_stubs:
    path: /Users/ericm/reliveit/checkout/ericmartineau/sunny_service_stubs
  sunny_sdk_core:
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_sdk_core
  worker_service:
    path: /Users/ericm/reliveit/checkout/SunnyApp/worker_service
  dartxx:
    path: /Users/ericm/reliveit/checkout/ericmartineau/dartxx
  sunny_dart:
    path: /Users/ericm/reliveit/checkout/SunnyApp/sunny_dart
dev_dependencies:
  build_runner: ^2.4.0
  provider: ^6.0.5
flutter:
  assets:
    - ./lib/upload_large_file.grunt.dart.js
    - ./lib/upload_large_file.grunt.dart.js.map
    - ./lib/upload_large_file.grunt.dart.js.tar.gz
