name: file_upload_service
version: 1.5.1
description: File uploading
repository: https://github.com/ericmartineau/file_upload_service.git
environment: 
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies: 
  buffer: ^1.1.1
  collection_diff: ^2.0.3+6
  observable_collections: ^0.7.1
  dartx: ^0.7.1
  dio: ^4.0.6
  http: ^0.13.4
  logging: ^1.0.2
  logging_config: ^0.6.7+7
  permission_handler: ^9.2.0
  pfile: ^2.2.0
  semaphore: ^0.2.1
  stream_transform: ^2.0.0
  grunt_web_worker_gen: ^0.8.7+1
  graphql: ^5.1.1
  gql_http_link: ^0.4.2
  sunny_service_stubs: ^0.5.1
  sunny_sdk_core: ^2.5.0
  worker_service: ^0.7.4
  dartxx: ^0.5.5
  sunny_dart: ^0.11.1
dev_dependencies: 
  build_runner: ^2.1.10
  provider: ^6.0.2
flutter: 
  assets: 
    - upload_large_file.grunt.dart.js
    - upload_large_file.grunt.dart.js.map
    - upload_large_file.grunt.dart.js.tar.gz
