name: file_upload_service
version: 1.5.1
description: File uploading
repository: https://github.com/ericmartineau/file_upload_service.git
environment: 
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'
dependencies: 
  buffer: ^1.1.1
  dartx: ^1.1.0
  dio: ^5.2.0+1
  http: ^1.0.0
  logging: 1.2.0
  permission_handler: ^10.2.0
  semaphore: ^0.2.1
  stream_transform: ^2.1.0
  graphql: ^5.2.0-beta.3
  gql_http_link: ^1.0.0
  grunt_web_worker_gen: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/grunt_web_worker_gen
  collection_diff: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/collection_diff
  observable_collections: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/observable_collections
  logging_config: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/logging_config
  pfile: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/pfile
  sunny_service_stubs: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/sunny_service_stubs
  sunny_sdk_core: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/sunny_sdk_core
  worker_service: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/worker_service
  dartxx: 
    path: /Users/ericm/aesthetika/checkout/ericmartineau/dartxx
  sunny_dart: 
    path: /Users/ericm/aesthetika/checkout/SunnyApp/sunny_dart
dev_dependencies: 
  build_runner: 2.4.4
  provider: ^6.0.5
flutter: 
  assets: 
    - ./lib/upload_large_file.grunt.dart.js
    - ./lib/upload_large_file.grunt.dart.js.map
    - ./lib/upload_large_file.grunt.dart.js.tar.gz
